export type Bank = 'Samlink';
export type BIC =   'HELSFIHH' | 'BIGKFIH1' | 'CITIFIHX' | 'DABAFIHH' | 'DABAFIHX' | 'DNBAFIHX' | 'HANDFIHH' | 'HOLVFIHH' | 'NDEAFIHH' | 'OMASP' | 'OKOYFIHH' | 'POPFFI22' | 'SBANFIHH' | 'ESSEFIHX' | 'SWEDFIHH' | 'ITELFIHH' | 'AABAFI22';
export type Code = 'BANK';
export type Command = 'GetCertificate' | 'RenewCertificate';
export type Country = 'FI' | 'SE'; // Finland, Sweden,
export type Currency = 'EUR' | 'USD';
export type Environment = 'TEST' | 'PRODUCTION';
export type FileStatus = 'NEW' | 'DLD' | 'ALL';
export type FileType = 'XL' | 'XP' | 'XT';
export type Language = 'FI' | 'EN' | 'SV';
export type OutputEncoding = 'utf-8' | 'base64';
export type PaymentMethod = 'TRF';
export type ServiceLevel = 'SLEV';
export type Status = 'WFP' | 'WFC' | 'FWD' | 'DLD' | 'DEL' | 'NEW' | 'KIN' |  'ALL' | '';
